Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
import turtle

count = 10
while (count > 0):
    turtle.forward(100)
    turtle.left(30)
    count = count - 1

    
turtle.forward(500)
Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    turtle.forward(500)
  File "<string>", line 5, in forward
turtle.Terminator
turtle.reset()
turtle.forward(500)
turtle.left(90)
turtle.forward(500)
turtle.left(90)
turtle.forward(500)
turtle.left(90)
turtle.forward(500)
turtle.left(90)
turtle.penup()
turtle.forward(100)
turtle.pendown()
turtle.left(90)
turtle.forward(500)
turtle.right(90)
turtle.penup()
turtle.forward(100)
turtle.right(90)
turtle.forward(500)
turtle.left(90)
turtle.penup()
turtle.forward(100)
turtle.left(90)
turtle.undo()
turtle.undo()
turtle.left(90)
turtle.pendown()
turtle.forward(500)
turtle.penup()
turtle.right(90)
turtle.forward(100)
>>> turtle.pendown()
>>> turtle.right(90)
>>> turtle.forward(500)
>>> turtle.penup()
>>> turtle.left(90)
>>> turtle.forward(100)
>>> turtle.left(90)
>>> turtle.pendown()
>>> turtle.forward(500)
>>> turtle.left(90)
>>> turtle.penup()
>>> turtle.forward(400)
>>> turtle.left(90)
>>> turtle.forward(400)
>>> turtle.left(90)
>>> turtle.pendown()
>>> turtle.forward(500)
>>> turtle.left(90)
>>> turtle.penup()
>>> turtle.forward(100)
>>> turtle.left(90)
turtle.left(90)
>>> turtle.pendown()
>>> turtle.forward(500)
>>> turtle.right(90)
>>> turtle.penup()
>>> turtle.forward(100)
>>> turtle.pendown()
>>> turtle.right(90)
>>> turtle.forward(500)
>>> turtle.forward(500)
>>> turtle.penup()
>>> turtle.left(90)
>>> turtle.forward(100)
>>> turtle.left(90)
>>> turtle.forward(500)
>>> turtle.undo()
>>> turtle.pendown()
>>> turtle.forward(500)
